#!/usr/bin/env bun
// bunny/templates/create-bunnyx/index.ts
// Usage: bunx create-bunnyx my-app

import { join } from 'path';
import { mkdirSync, writeFileSync, existsSync } from 'fs';

const name = process.argv[2];

if (!name) {
  console.error('\nUsage: bunx create-bunnyx <app-name>\n');
  process.exit(1);
}

const dest = join(process.cwd(), name);

if (existsSync(dest)) {
  console.error(`\nDirectory "${name}" already exists\n`);
  process.exit(1);
}

console.log(`\n  🐰 Creating Bunnyx app: \x1b[1m${name}\x1b[0m\n`);

// ─── All files ────────────────────────────────────────────────────────────────

const files: Record<string, string> = {

  // ── Root config ─────────────────────────────────────────────────────────────

  'package.json': JSON.stringify({
    name,
    version: '0.1.0',
    type: 'module',
    scripts: {
      dev:   'bunnyx dev',
      build: 'bunnyx build',
      start: 'bunnyx start',
    },
    dependencies: {
      bunny:             '^1.0.0',
      bertui:            '^1.3.0',
      elysia:            'latest',
      '@elysiajs/cors':  'latest',
      '@elysiajs/eden':  'latest',
    },
    devDependencies: {
      'bun-types': 'latest',
    },
  }, null, 2),

  // bunnyx.config.ts — replaces BOTH bertui.config.js AND elysia config
  // bertui.config.js is auto-generated by Bunnyx from the bertui block here
  'bunnyx.config.ts': `import type { BunnyConfig } from 'bunnyx';

export default {
  // Elysia entry — exact format from \`bun create elysia\`
  server: './src/index.ts',

  // BertUI config — same fields as bertui.config.js, passed through directly
  bertui: {
    baseUrl: 'http://localhost:3000',
    siteName: '${name}',
    importhow: {
      // Add import aliases here — same as bertui importhow
      // components: './src/components',
      // ui: './src/components/ui',
    },
    meta: {
      title: '${name}',
      description: 'Built with Bunnyxxx — BertUI + Elysia',
      lang: 'en',
    },
  },

  dev:   { port: 3000 },
  build: { outDir: 'dist' },
} satisfies BunnyConfig;
`,

  'tsconfig.json': JSON.stringify({
    compilerOptions: {
      strict: true,
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      jsx: 'react',
      jsxFactory: 'React.createElement',
      jsxFragmentFactory: 'React.Fragment',
      allowImportingTsExtensions: true,
      noEmit: true,
      paths: {
        // @bunny/api → auto-generated type-safe client
        // Regenerated every time `bunnyx dev` starts or Elysia files change
        '@bunny/api': ['./.bunny/api-client.ts'],
      },
    },
    include: ['src/**/*', 'bunnyx.config.ts', 'bunny-env.d.ts', '.bunny/**/*'],
  }, null, 2),

  '.env': `# Environment variables
APP_NAME="${name}"
# DATABASE_URL=...
`,

  '.gitignore': `node_modules/
dist/
.bertui/
.bertuibuild/
.bunny/
bertui.config.js
bunny-env.d.ts
*.log
`,

  // ── Elysia backend — exact bun create elysia structure ────────────────────

  // Main entry — mirrors `bun create elysia` output exactly
  // .listen(3000) is here as per the official template
  // Bunny handles it: stops the orphan server, mounts routes via .use()
  'src/index.ts': `import { Elysia } from 'elysia'
import { cors } from '@elysiajs/cors'
import { usersRoutes } from './api/users'
import { postsRoutes } from './api/posts'

const app = new Elysia()
  .use(cors())
  .use(usersRoutes)
  .use(postsRoutes)
  .listen(3000)

console.log(\`🦊 Elysia is running at \${app.server?.hostname}:\${app.server?.port}\`)

// Export type for the type-safe client
export type App = typeof app
export default app
`,

  // API routes split by domain — paste your existing Elysia routes here
  'src/api/users.ts': `import { Elysia, t } from 'elysia'

export const usersRoutes = new Elysia({ prefix: '/api/users' })
  .get('/', () => ({
    users: [
      { id: 1, name: 'Alice' },
      { id: 2, name: 'Bob' },
    ],
  }))

  .get('/:id', ({ params }) => ({
    user: { id: Number(params.id), name: 'Alice' },
  }))

  .post('/', ({ body }) => ({
    created: { id: Date.now(), ...body },
  }), {
    body: t.Object({
      name: t.String(),
    }),
  })
`,

  'src/api/posts.ts': `import { Elysia, t } from 'elysia'

export const postsRoutes = new Elysia({ prefix: '/api/posts' })
  .get('/', () => ({
    posts: [
      { id: 1, title: 'Hello World', slug: 'hello-world' },
      { id: 2, title: 'Getting Started', slug: 'getting-started' },
    ],
  }))

  .get('/:slug', ({ params }) => ({
    post: { slug: params.slug, title: 'Hello World', content: '...' },
  }))
`,

  // Optional type-safe client using bunny/client
  'src/api.ts': `// Optional: type-safe API client powered by bunny/client
// Usage: const { data } = await api.api.users.get()
import { createApiClient } from 'bunnyx/client'
import type { App } from './index'

export const api = createApiClient<App>()
`,

  // ── BertUI frontend — exact same structure as a BertUI app ────────────────

  'src/main.jsx': `import React from 'react'
import { createRoot } from 'react-dom/client'
import App from 'bertui/app'

const root = createRoot(document.getElementById('root'))
root.render(<App />)
`,

  'src/pages/index.jsx': `import React, { useState, useEffect } from 'react'
import { Link } from 'bertui/router'
// @bunny/api is auto-generated by \`bunnyx dev\` from your Elysia App type
// Full autocomplete: api.api.users.get() → { data: { users: User[] } }
import { api } from '@bunny/api'

export const title = 'Home — ${name}'
export const description = 'Built with Bunnyxx'

export default function HomePage() {
  const [users, setUsers]   = useState([])
  const [posts, setPosts]   = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([
      api.api.users.get(),
      api.api.posts.get(),
    ]).then(([u, p]) => {
      setUsers(u.data?.users ?? [])
      setPosts(p.data?.posts ?? [])
      setLoading(false)
    })
  }, [])

  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui', maxWidth: '680px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '2.5rem', marginBottom: '0.25rem' }}>🐰 ${name}</h1>
      <p style={{ color: '#6b7280', marginBottom: '2rem', fontSize: '0.9rem' }}>
        BertUI + Elysia via Bunnyx · <code style={{ background: '#f3f4f6', padding: '0.1em 0.4em', borderRadius: 4 }}>@bunny/api</code> is active
      </p>

      {loading ? (
        <p style={{ color: '#9ca3af' }}>Loading from API...</p>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
          <section>
            <h2 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.75rem', color: '#374151' }}>
              /api/users
            </h2>
            <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              {users.map((u) => (
                <li key={u.id} style={{ padding: '0.6rem 0.9rem', background: '#f9fafb', borderRadius: 6, border: '1px solid #e5e7eb', fontSize: '0.9rem' }}>
                  {u.name}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.75rem', color: '#374151' }}>
              /api/posts
            </h2>
            <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              {posts.map((p) => (
                <li key={p.id} style={{ padding: '0.6rem 0.9rem', background: '#f9fafb', borderRadius: 6, border: '1px solid #e5e7eb', fontSize: '0.9rem' }}>
                  {p.title}
                </li>
              ))}
            </ul>
          </section>
        </div>
      )}

      <nav style={{ marginTop: '2rem', display: 'flex', gap: '1.5rem' }}>
        <Link to="/about" style={{ color: '#10b981', fontSize: '0.9rem' }}>About →</Link>
        <Link to="/blog" style={{ color: '#10b981', fontSize: '0.9rem' }}>Blog →</Link>
      </nav>
    </main>
  )
}
`,

  'src/pages/about.jsx': `import React from 'react'
import { Link } from 'bertui/router'

export const title = 'About — ${name}'

export default function AboutPage() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui', maxWidth: '640px', margin: '0 auto' }}>
      <h1>About</h1>
      <p style={{ color: '#6b7280', marginTop: '0.5rem', lineHeight: 1.6 }}>
        This app is powered by <strong>Bunny</strong> — BertUI for the frontend,
        Elysia for the backend, running in one Bun server on one port.
      </p>

      <ul style={{ marginTop: '1.5rem', lineHeight: 2.2 }}>
        <li>📄 Pages live in <code>src/pages/</code></li>
        <li>🔌 API routes live in <code>src/api/</code></li>
        <li>🚪 Entry is <code>src/index.ts</code></li>
        <li>⚙️  Config is <code>bunnyx.config.ts</code></li>
      </ul>

      <Link to="/" style={{ color: '#10b981', display: 'inline-block', marginTop: '1.5rem' }}>← Home</Link>
    </main>
  )
}
`,

  'src/pages/blog/index.jsx': `import React, { useState, useEffect } from 'react'
import { Link } from 'bertui/router'

export const title = 'Blog — ${name}'

export default function BlogPage() {
  const [posts, setPosts] = useState([])

  useEffect(() => {
    fetch('/api/posts')
      .then(r => r.json())
      .then(d => setPosts(d.posts))
  }, [])

  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui', maxWidth: '640px', margin: '0 auto' }}>
      <h1>Blog</h1>
      <div style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {posts.map(p => (
          <Link key={p.id} to={\`/blog/\${p.slug}\`} style={{ textDecoration: 'none', color: 'inherit' }}>
            <div style={{ padding: '1rem', border: '1px solid #e5e7eb', borderRadius: '8px' }}>
              <h2 style={{ margin: 0, fontSize: '1.1rem' }}>{p.title}</h2>
            </div>
          </Link>
        ))}
      </div>
      <Link to="/" style={{ color: '#10b981', display: 'inline-block', marginTop: '1.5rem' }}>← Home</Link>
    </main>
  )
}
`,

  'src/pages/blog/[slug].jsx': `import React, { useState, useEffect } from 'react'
import { useRouter, Link } from 'bertui/router'

export const title = 'Post'

export default function BlogPostPage() {
  const { params } = useRouter()
  const [post, setPost] = useState(null)

  useEffect(() => {
    fetch(\`/api/posts/\${params.slug}\`)
      .then(r => r.json())
      .then(d => setPost(d.post))
  }, [params.slug])

  if (!post) return <p style={{ padding: '2rem', fontFamily: 'system-ui' }}>Loading...</p>

  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui', maxWidth: '640px', margin: '0 auto' }}>
      <h1>{post.title}</h1>
      <p style={{ color: '#6b7280', marginTop: '0.5rem' }}>{post.content}</p>
      <Link to="/blog" style={{ color: '#10b981', display: 'inline-block', marginTop: '1.5rem' }}>← Blog</Link>
    </main>
  )
}
`,

  // ── Styles — same as BertUI app ───────────────────────────────────────────

  'src/styles/global.css': `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: #ffffff;
  color: #111827;
  line-height: 1.5;
}

a { color: #10b981; }
code { font-family: 'Monaco', 'Menlo', monospace; font-size: 0.875em; background: #f3f4f6; padding: 0.1em 0.3em; border-radius: 3px; }
`,

  // ── Public ────────────────────────────────────────────────────────────────

  'public/favicon.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <text y=".9em" font-size="90">🐰</text>
</svg>
`,

  // ── README ────────────────────────────────────────────────────────────────

  'README.md': `# ${name}

> 🐰 Built with [Bunny](https://github.com/BunElysiaReact/bunny) — BertUI + Elysia in one server

## Quick Start

\`\`\`bash
bun install
bun run dev        # → http://localhost:3000
\`\`\`

## Commands

| Command          | Description                       |
|-----------------|-----------------------------------|
| \`bun run dev\`   | Development server + HMR          |
| \`bun run build\` | Production build → dist/          |
| \`bun run start\` | Start production server           |

## Structure

\`\`\`
src/
├── index.ts           # Elysia entry (bun create elysia format)
├── api/
│   ├── users.ts       # /api/users routes
│   └── posts.ts       # /api/posts routes
├── api.ts             # Type-safe client (optional)
├── main.jsx           # BertUI entry
├── pages/             # File-based routing
│   ├── index.jsx      → /
│   ├── about.jsx      → /about
│   └── blog/
│       ├── index.jsx  → /blog
│       └── [slug].jsx → /blog/:slug
├── components/        # React components
└── styles/
    └── global.css
\`\`\`

## Migrating existing apps

**From a BertUI app:** copy \`src/pages\`, \`src/components\`, \`src/styles\` as-is.
Move \`bertui.config.js\` settings into the \`bertui\` block in \`bunnyx.config.ts\`.

**From a \`bun create elysia\` app:** copy \`src/index.ts\` and \`src/api/\` as-is.
No changes needed.
`,
};

// ─── Write all files ──────────────────────────────────────────────────────────

for (const [filePath, content] of Object.entries(files)) {
  const fullPath = join(dest, filePath);
  const dir = fullPath.substring(0, fullPath.lastIndexOf('/'));
  mkdirSync(dir, { recursive: true });
  writeFileSync(fullPath, content, 'utf-8');
  console.log(`  \x1b[32m+\x1b[0m ${filePath}`);
}

console.log(`
  \x1b[32m\x1b[1m✓ Created ${name}\x1b[0m

  \x1b[1mNext steps:\x1b[0m

    cd ${name}
    bun install
    bun run dev

  \x1b[90mhttp://localhost:3000\x1b[0m
`);

