// bunnyx/src/typegen/index.ts

import { join, relative } from 'path';
import { mkdirSync, existsSync } from 'fs';

export async function generateTypes(root: string, serverPath: string): Promise<void> {
  // bunnyx-api/ lives at project root — outside src/ so bertui never scans it
  const bunnyDir   = join(root, 'bunnyx-api');
  const dtsPath    = join(root, 'bunnyx-env.d.ts');
  const clientPath = join(bunnyDir, 'api-client.js');

  mkdirSync(bunnyDir, { recursive: true });

  await Promise.all([
    writeDts(dtsPath, root, serverPath),
    writeClient(clientPath),
  ]);
}

async function writeDts(dtsPath: string, root: string, serverPath: string) {
  const relServer = relative(root, serverPath)
    .replace(/\.(ts|tsx)$/, '')
    .replace(/\\/g, '/');

  const content = `// Auto-generated by Bunnyx — do not edit
/// <reference types="bun-types" />

declare module '@bunnyx/api' {
  import type { App } from './${relServer}';
  import type { treaty } from '@elysiajs/eden';
  export declare const api: ReturnType<typeof treaty<App>>;
  export declare function createClient<T extends Record<string, any>>(
    baseUrl?: string,
    options?: Parameters<typeof treaty>[1]
  ): ReturnType<typeof treaty<T>>;
}
`;
  await Bun.write(dtsPath, content);
}

async function writeClient(clientPath: string) {
  const content = `// Auto-generated by Bunnyx — do not edit
import { treaty } from '@elysiajs/eden';

function getBaseUrl() {
  if (typeof window !== 'undefined') return window.location.origin;
  return 'http://localhost:3000';
}

export function createClient(baseUrl, options) {
  return treaty(baseUrl ?? getBaseUrl(), options);
}

export const api = treaty(getBaseUrl());
`;
  await Bun.write(clientPath, content);
}

export async function patchTsConfig(root: string): Promise<boolean> {
  const tsconfigPath = join(root, 'tsconfig.json');
  if (!existsSync(tsconfigPath)) return false;

  try {
    const raw      = await Bun.file(tsconfigPath).text();
    const clean    = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
    const tsconfig = JSON.parse(clean);

    if (tsconfig?.compilerOptions?.paths?.['@bunnyx/api']) return false;

    tsconfig.compilerOptions       ??= {};
    tsconfig.compilerOptions.paths ??= {};
    tsconfig.compilerOptions.paths['@bunnyx/api'] = ['./bunnyx-api/api-client.js'];

    if (Array.isArray(tsconfig.include) && !tsconfig.include.includes('bunnyx-api/**/*')) {
      tsconfig.include.push('bunnyx-api/**/*');
    }

    await Bun.write(tsconfigPath, JSON.stringify(tsconfig, null, 2));
    return true;
  } catch {
    return false;
  }
}