// bunny/src/typegen/index.ts
//
// Generates two files at dev startup (and on every Elysia file change):
//
//   1. bunnyx-env.d.ts       — ambient module declaration for `@bunnyx/api`
//   2. .bunnyx/api-client.ts — thin wrapper around Eden Treaty (the real thing)
//
// Usage in any BertUI component, zero config:
//
//   import { api } from '@bunnyx/api'
//   const { data } = await api.api.users.get()
//   //      ^ fully typed from your Elysia App type via Eden Treaty

import { join, relative } from 'path';
import { mkdirSync, existsSync } from 'fs';

// ─── Main export ─────────────────────────────────────────────────────────────

export async function generateTypes(root: string, serverPath: string): Promise<void> {
  const bunnyDir   = join(root, '.bunnyx');
  const dtsPath    = join(root, 'bunnyx-env.d.ts');
  const clientPath = join(bunnyDir, 'api-client.ts');

  mkdirSync(bunnyDir, { recursive: true });

  // e.g. "../src/index" (relative from .bunnyx/ to src/index.ts, no extension)
  const relToServer = relative(bunnyDir, serverPath)
    .replace(/\.(ts|tsx)$/, '')
    .replace(/\\/g, '/');

  await Promise.all([
    writeDts(dtsPath, root, serverPath),
    writeClient(clientPath, relToServer),
  ]);
}

// ─── 1. bunnyx-env.d.ts ───────────────────────────────────────────────────────
// Ambient module declaration so TypeScript knows what `@bunnyx/api` exports.
// Lives at project root so it's picked up by the user's tsconfig automatically.

async function writeDts(dtsPath: string, root: string, serverPath: string) {
  const relServer = relative(root, serverPath)
    .replace(/\.(ts|tsx)$/, '')
    .replace(/\\/g, '/');

  const content = `// Auto-generated by Bunnyxx — do not edit
// Restart \`bunnyx dev\` to refresh after changing Elysia routes

/// <reference types="bun-types" />

declare module '@bunnyx/api' {
  import type { App } from './${relServer}';
  import type { treaty } from '@elysiajs/eden';

  /** Type-safe Eden Treaty client — auto-wired from your Elysia App type */
  export declare const api: ReturnType<typeof treaty<App>>;

  /** Create a custom-configured Eden Treaty client */
  export declare function createClient<T extends Record<string, any>>(
    baseUrl?: string,
    options?: Parameters<typeof treaty>[1]
  ): ReturnType<typeof treaty<T>>;
}
`;

  await Bun.write(dtsPath, content);
}

// ─── 2. .bunnyx/api-client.ts ─────────────────────────────────────────────────
// The actual runtime module behind `@bunnyx/api`.
// Uses Eden Treaty directly — no reimplementation, just wiring.

async function writeClient(clientPath: string, relToServer: string) {
  const content = `// Auto-generated by Bunnyxx — do not edit
// Runtime for \`import { api } from '@bunnyx/api'\`
// Powered by Eden Treaty (@elysiajs/eden) — Elysia's official client

import { treaty } from '@elysiajs/eden';
import type { App } from '${relToServer}';

function getBaseUrl(): string {
  if (typeof window !== 'undefined') return window.location.origin;
  return 'http://localhost:3000';
}

/**
 * Create a typed Eden Treaty client pointed at any base URL.
 * @example
 *   const client = createClient<App>('https://api.myapp.com')
 */
export function createClient<T extends Record<string, any>>(
  baseUrl?: string,
  options?: Parameters<typeof treaty>[1]
) {
  return treaty<T>(baseUrl ?? getBaseUrl(), options);
}

/**
 * Pre-built type-safe client — auto-pointed at the current origin.
 * @example
 *   import { api } from '@bunnyx/api'
 *   const { data, error } = await api.api.users.get()
 *   const { data }        = await api.api.users.post({ body: { name: 'Alice' } })
 *   const { data }        = await api.api.users({ id: '1' }).get()
 */
export const api = treaty<App>(getBaseUrl());
`;

  await Bun.write(clientPath, content);
}

// ─── tsconfig patcher ─────────────────────────────────────────────────────────
// Adds @bunnyx/api path alias to tsconfig.json so IDE autocomplete works.
// Idempotent — only writes if the alias isn't already there.

export async function patchTsConfig(root: string): Promise<boolean> {
  const tsconfigPath = join(root, 'tsconfig.json');
  if (!existsSync(tsconfigPath)) return false;

  try {
    const raw      = await Bun.file(tsconfigPath).text();
    const clean    = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
    const tsconfig = JSON.parse(clean);

    if (tsconfig?.compilerOptions?.paths?.['@bunnyx/api']) return false;

    tsconfig.compilerOptions       ??= {};
    tsconfig.compilerOptions.paths ??= {};
    tsconfig.compilerOptions.paths['@bunnyx/api'] = ['./.bunnyx/api-client.ts'];

    // Ensure .bunnyx/ is in include so TS picks up the generated client
    if (Array.isArray(tsconfig.include) && !tsconfig.include.includes('.bunnyx/**/*')) {
      tsconfig.include.push('.bunnyx/**/*');
    }

    await Bun.write(tsconfigPath, JSON.stringify(tsconfig, null, 2));
    return true;
  } catch {
    return false;
  }
}
