// bunnyx/src/typegen/index.ts

import { join, relative, dirname } from 'path';
import { mkdirSync, existsSync } from 'fs';

export async function generateTypes(root: string, serverPath: string): Promise<void> {
  const bunnyDir   = join(root, 'bunnyx-api');
  const dtsPath    = join(root, 'bunnyx-env.d.ts');
  const clientPath = join(bunnyDir, 'api-client.ts');

  mkdirSync(bunnyDir, { recursive: true });

  await Promise.all([
    writeDts(dtsPath, root),
    writeClient(clientPath, serverPath, root),
  ]);
}

// bunnyx-env.d.ts just tells TS: "@bunnyx/api" = this file
// The actual types live in api-client.ts — no redeclaration
async function writeDts(dtsPath: string, root: string) {
  const content = `// Auto-generated by Bunnyx — do not edit
/// <reference types="bun-types" />
`;
  await Bun.write(dtsPath, content);
}

async function writeClient(clientPath: string, serverPath: string, root: string) {
  const relServer = relative(dirname(clientPath), serverPath)
    .replace(/\.(ts|tsx)$/, '')
    .replace(/\\/g, '/');

  const content = `// Auto-generated by Bunnyx — do not edit
import { treaty } from '@elysiajs/eden';
import type { App } from '${relServer}';

function getBaseUrl() {
  if (typeof window !== 'undefined') return window.location.origin;
  return 'http://localhost:3000';
}

export const api = treaty<App>(getBaseUrl());

export function createClient(baseUrl?: string) {
  return treaty<App>(baseUrl ?? getBaseUrl());
}
`;
  await Bun.write(clientPath, content);
}

export async function patchTsConfig(root: string): Promise<boolean> {
  const tsconfigPath = join(root, 'tsconfig.json');
  if (!existsSync(tsconfigPath)) return false;

  try {
    const raw      = await Bun.file(tsconfigPath).text();
    const clean    = raw.replace(/\/\/.*$/gm, '').replace(/\/\*[\s\S]*?\*\//g, '');
    const tsconfig = JSON.parse(clean);

    if (tsconfig?.compilerOptions?.paths?.['@bunnyx/api']) return false;

    tsconfig.compilerOptions          ??= {};
    tsconfig.compilerOptions.paths    ??= {};
    // Alias points directly to the implementation file — single source of truth
    tsconfig.compilerOptions.paths['@bunnyx/api'] = ['./bunnyx-api/api-client.ts'];

    if (!Array.isArray(tsconfig.include)) tsconfig.include = ['src'];
    if (!tsconfig.include.includes('bunnyx-api/**/*')) tsconfig.include.push('bunnyx-api/**/*');

    await Bun.write(tsconfigPath, JSON.stringify(tsconfig, null, 2));
    return true;
  } catch {
    return false;
  }
}