import React, { useState, useEffect } from 'react'
import { Link } from 'bertui/router'
// @bunny/api is auto-generated by `bunnyx dev` from your Elysia App type
// Full autocomplete: api.api.users.get() → { data: { users: User[] } }
import { api } from '@bunnyx/api'

export const title = 'Home — bunnyx-test'
export const description = 'Built with Bunnyxx'

export default function HomePage() {
  const [users, setUsers]   = useState([])
  const [posts, setPosts]   = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([
      api.api.users.get(),
      api.api.posts.get(),
    ]).then(([u, p]) => {
      setUsers(u.data?.users ?? [])
      setPosts(p.data?.posts ?? [])
      setLoading(false)
    })
  }, [])

  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui', maxWidth: '680px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '2.5rem', marginBottom: '0.25rem' }}>🐰 bunnyx-test</h1>
      <p style={{ color: '#6b7280', marginBottom: '2rem', fontSize: '0.9rem' }}>
        BertUI + Elysia via Bunnyx · <code style={{ background: '#f3f4f6', padding: '0.1em 0.4em', borderRadius: 4 }}>@bunny/api</code> is active
      </p>

      {loading ? (
        <p style={{ color: '#9ca3af' }}>Loading from API...</p>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
          <section>
            <h2 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.75rem', color: '#374151' }}>
              /api/users
            </h2>
            <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              {users.map((u) => (
                <li key={u.id} style={{ padding: '0.6rem 0.9rem', background: '#f9fafb', borderRadius: 6, border: '1px solid #e5e7eb', fontSize: '0.9rem' }}>
                  {u.name}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: '0.75rem', color: '#374151' }}>
              /api/posts
            </h2>
            <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
              {posts.map((p) => (
                <li key={p.id} style={{ padding: '0.6rem 0.9rem', background: '#f9fafb', borderRadius: 6, border: '1px solid #e5e7eb', fontSize: '0.9rem' }}>
                  {p.title}
                </li>
              ))}
            </ul>
          </section>
        </div>
      )}

      <nav style={{ marginTop: '2rem', display: 'flex', gap: '1.5rem' }}>
        <Link to="/about" style={{ color: '#10b981', fontSize: '0.9rem' }}>About →</Link>
        <Link to="/blog" style={{ color: '#10b981', fontSize: '0.9rem' }}>Blog →</Link>
      </nav>
    </main>
  )
}
