// Auto-generated by Bunnyx — do not edit
/// <reference types="bun-types" />

declare module '@bunnyx/api' {
  import type { App } from './src/index';
  import type { treaty } from '@elysiajs/eden';
  export declare const api: ReturnType<typeof treaty<App>>;
  export declare function createClient<T extends Record<string, any>>(
    baseUrl?: string,
    options?: Parameters<typeof treaty>[1]
  ): ReturnType<typeof treaty<T>>;
}
