// bunny/src/config/index.ts

import { join, resolve } from 'path';
import { existsSync } from 'fs';
import type { BunnyConfig, ResolvedBunnyConfig, BertuiBridgeConfig } from '../types/index.ts';

const CONFIG_FILES = [
  'bunnyx.config.ts',
  'bunnyx.config.js',
];

// ─── Defaults ────────────────────────────────────────────────────────────────
// server default matches `bun create elysia` output exactly → src/index.ts

const DEFAULTS: ResolvedBunnyConfig = {
  server:  './src/index.ts',
  bertui:  {},
  dev:     { port: 3000, host: 'localhost' },
  build:   { outDir: 'dist' },
  root:    process.cwd(),
};

// ─── Loader ──────────────────────────────────────────────────────────────────

export async function loadBunnyConfig(root: string = process.cwd()): Promise<ResolvedBunnyConfig> {
  let userConfig: BunnyConfig = {};

  for (const file of CONFIG_FILES) {
    const configPath = join(root, file);
    if (existsSync(configPath)) {
      try {
        const source = await Bun.file(configPath).text();
        const transpiler = new Bun.Transpiler({
          loader: file.endsWith('.ts') ? 'ts' : 'js',
          target: 'bun',
        });
        let code = await transpiler.transform(source);
        // Strip satisfies keyword (TS-only, not valid in eval)
        code = code.replace(/\s+satisfies\s+\w+/g, '');
        code = code.replace(/export\s+default\s+/, 'globalThis.__bunnyConfig = ');
        const fn = new Function('globalThis', code);
        fn(globalThis);
        userConfig = (globalThis as any).__bunnyConfig ?? {};
        delete (globalThis as any).__bunnyConfig;
        break;
      } catch (err: any) {
        console.warn(`⚠  Could not load ${file}: ${err.message}`);
      }
    }
  }

  const resolved = mergeConfig(DEFAULTS, userConfig, root);

  // Write bertui.config.js so BertUI's own loadConfig() picks up all settings
  // This means importhow, meta, robots, appShell all flow through correctly
  await writeBertuiConfig(root, resolved.bertui);

  return resolved;
}

// ─── Write bertui.config.js from the bertui block ────────────────────────────
// BertUI's internals call loadConfig(root) which reads bertui.config.js
// We generate this file so all BertUI features (importhow, meta, etc.) work

async function writeBertuiConfig(root: string, bertui: BertuiBridgeConfig) {
  const configPath = join(root, 'bertui.config.js');

  // Don't overwrite if user has their own — they may have migrated manually
  // But do write if it doesn't exist, or if it was previously written by Bunnyx
  const content = `// Auto-generated by Bunnyxx — do not edit manually
// Edit the 'bertui' block in bunnyx.config.ts instead
export default ${JSON.stringify({
    baseUrl:  bertui.baseUrl  ?? 'http://localhost:3000',
    siteName: bertui.siteName ?? 'Bunny App',
    importhow: bertui.importhow ?? {},
    meta:      bertui.meta      ?? {},
    appShell:  bertui.appShell  ?? {},
    robots:    bertui.robots    ?? { disallow: [], crawlDelay: null },
  }, null, 2)};
`;

  await Bun.write(configPath, content);
}

// ─── Merge ───────────────────────────────────────────────────────────────────

function mergeConfig(
  defaults: ResolvedBunnyConfig,
  user: BunnyConfig,
  root: string
): ResolvedBunnyConfig {
  return {
    root,
    server: resolve(root, user.server ?? defaults.server),
    bertui: { ...defaults.bertui, ...(user.bertui ?? {}) },
    dev:    { ...defaults.dev,    ...(user.dev    ?? {}) },
    build:  { ...defaults.build,  ...(user.build  ?? {}) },
  };
}

export { DEFAULTS };
