// bunnyx/src/config/index.ts

import { join, resolve } from 'path';
import { existsSync } from 'fs';
import type { BunnyConfig, ResolvedBunnyConfig, BertuiBridgeConfig } from '../types/index.ts';

const CONFIG_FILES = [
  'bunnyx.config.ts',
  'bunnyx.config.js',
];

const DEFAULTS: ResolvedBunnyConfig = {
  server: './src/index.ts',
  bertui: {},
  dev:    { port: 3000, host: 'localhost' },
  build:  { outDir: 'dist' },
  root:   process.cwd(),
  bypass: [], // ← default empty
};

export async function loadBunnyConfig(root: string = process.cwd()): Promise<ResolvedBunnyConfig> {
  let userConfig: BunnyConfig = {};

  for (const file of CONFIG_FILES) {
    const configPath = join(root, file);
    if (existsSync(configPath)) {
      try {
        const source = await Bun.file(configPath).text();
        const transpiler = new Bun.Transpiler({
          loader: file.endsWith('.ts') ? 'ts' : 'js',
          target: 'bun',
        });
        let code = await transpiler.transform(source);
        code = code.replace(/\s+satisfies\s+\w+/g, '');
        code = code.replace(/export\s+default\s+/, 'globalThis.__bunnyConfig = ');
        const fn = new Function('globalThis', code);
        fn(globalThis);
        userConfig = (globalThis as any).__bunnyConfig ?? {};
        delete (globalThis as any).__bunnyConfig;
        break;
      } catch (err: any) {
        console.warn(`⚠  Could not load ${file}: ${err.message}`);
      }
    }
  }

  const resolved = mergeConfig(DEFAULTS, userConfig, root);
  await writeBertuiConfig(root, resolved.bertui);
  return resolved;
}

async function writeBertuiConfig(root: string, bertui: BertuiBridgeConfig) {
  const configPath = join(root, 'bertui.config.js');
  const content = `// Auto-generated by Bunnyx — do not edit manually
export default ${JSON.stringify({
    baseUrl:   bertui.baseUrl   ?? 'http://localhost:3000',
    siteName:  bertui.siteName  ?? 'Bunny App',
    importhow: bertui.importhow ?? {},
    meta:      bertui.meta      ?? {},
    appShell:  bertui.appShell  ?? {},
    robots:    bertui.robots    ?? { disallow: [], crawlDelay: null },
  }, null, 2)};
`;
  await Bun.write(configPath, content);
}

function mergeConfig(
  defaults: ResolvedBunnyConfig,
  user: BunnyConfig,
  root: string
): ResolvedBunnyConfig {
  return {
    root,
    server: resolve(root, user.server ?? defaults.server),
    bertui: { ...defaults.bertui, ...(user.bertui ?? {}) },
    dev:    { ...defaults.dev,    ...(user.dev    ?? {}) },
    build:  { ...defaults.build,  ...(user.build  ?? {}) },
    bypass: user.bypass ?? defaults.bypass,
  };
}

export { DEFAULTS };